#!/usr/bin/env python3
"""
This module implements a wrapper for the IRAF tasks 'qphot' (quick aperture
photometer) and 'txdump' (which print fields from selected records in an
APPHOT/DAOPHOT text database). The routines implemented in this module provide
a way to automatically do photometry on an image returning the records in a
qphot.QPhot instance. Temporary files are used for both qphot and txdump, but
they are automatically removed, so the entire process takes place in memory,
from the user's perspective.
"""
from __future__ import annotations

from pathlib import Path
import collections
import functools
import itertools
import logging
import math
import os
import re
import sys
import tempfile
import warnings

# LEMON modules
import fitsimage
import util
from util.context import tmp_chdir
from util.coords import load_coordinates
from util.io import clean_tmp_files
from util.log import StreamToWarningFilter, LoggerWriter

# Tell PyRAF to skip all graphics initialization and run in terminal-only mode.
# Otherwise we will get annoying warning messages (such as "could not open
# XWindow display" or "No graphics display available for this session") when
# working at a remote terminal or at a terminal without any X Windows support.
# Any tasks which attempt to display graphics will fail, of course, but we are
# not going to make use of any of them, anyway.
os.environ["PYRAF_NO_DISPLAY"] = "1"

# When PyRAF is imported, it creates, unless it already exists, a pyraf/
# directory for cache in the current working directory. It also complains that
# "Warning: no login.cl found" if this IRAF file cannot be found either. Avoid
# these two annoying messages, and do not clutter the filesystem with pyraf/
# directories, by temporarily changing the current working directory to that of
# LEMON, where the pyraf/ directory and login.cl were generated by setup.py.
with tmp_chdir(Path(__file__).resolve().parent):
    import pyraf.iraf
    from pyraf.iraf import digiphot, apphot  # 'digiphot.apphot' package

# Turn PyRAF process caching off; otherwise each child process might try to
# reuse the same IRAF executable, leading to flaky errors.
pyraf.iraf.prcacheOff()


def log_uncaught_exceptions(func):
    """Decorator to log uncaught exceptions with level DEBUG."""
    @functools.wraps(func)
    def wrapper(*args, **kwargs):
        try:
            return func(*args, **kwargs)
        except Exception:  # noqa: BLE001 - intentional broad catch
            etype, value, _tb = sys.exc_info()
            msg = "%s raised %s('%s')" % (func.__name__, etype.__name__, value)
            logging.debug(msg)
    return wrapper


# Quiet occasional destructor warnings from PyRAF's Subprocess
pyraf.subproc.Subprocess.__del__ = log_uncaught_exceptions(
    pyraf.subproc.Subprocess.__del__
)


class MissingFITSKeyword(RuntimeWarning):
    """Warning about keywords that cannot be read from a header (non-fatal)."""
    pass


typename = "QPhotResult"
field_names = "x, y, mag, sum, flux, stdev"


class QPhotResult(collections.namedtuple(typename, field_names)):
    """Encapsulate the photometry of an astronomical object."""

    def snr(self, gain):
        """Return the signal-to-noise ratio of the photometric measurement."""
        if gain <= 0:
            raise ValueError("CCD gain must be a positive value")

        # Avoid division by zero.
        if not self.sum:
            return 0.0

        if self.sum < 0.0:
            return -(abs(self.flux * gain) / math.sqrt(abs(self.sum * gain)))

        return (self.flux * gain) / math.sqrt(self.sum * gain)


class QPhot(list):
    """The photometry of an image, as returned by IRAF's qphot."""

    def __init__(self, img_path, coords_path):
        """Instantiate QPhot with the FITS path and a coordinates file."""
        list.__init__(self)
        self.image = fitsimage.FITSImage(img_path)
        self.coords_path = coords_path

        for ra, dec, pm_ra, pm_dec in load_coordinates(self.coords_path):
            if ra == 0 and dec == 0:
                msg = (
                    "the right ascension and declination of one or more "
                    "astronomical objects in '%s' is zero. This is a very bad "
                    "sign: these are the celestial coordinates that SExtractor "
                    "uses for sources detected on a FITS image that has not been "
                    "calibrated astrometrically (may that be your case?), and "
                    "without that it is impossible to do photometry on the "
                    "desired coordinates" % self.coords_path
                )
                warnings.warn(msg)
                break

            if pm_ra is not None or pm_dec is not None:
                msg = (
                    "at least one object in the '%s' file lists its proper "
                    "motions. This is not allowed. The coordinates must be "
                    "written to the file already adjusted for their proper "
                    "motions, as this class cannot apply any correction"
                    % self.coords_path
                )
                raise ValueError(msg)

    @property
    def path(self):
        """Return the path to the FITS image."""
        return self.image.path

    def clear(self):  # noqa: A003 - intentionally shadowing list.clear
        """Remove all the photometric measurements."""
        del self[:]

    def run(self, annulus, dannulus, aperture, exptimek, cbox=0):
        """Run IRAF's qphot on the FITS image and parse the results."""
        self.clear()  # empty object

        try:
            # Temporary file for qphot output (APPHOT text database)
            output_fd, qphot_output = tempfile.mkstemp(
                prefix=Path(self.path).name, suffix=".qphot_output", text=True
            )
            os.close(output_fd)
            os.unlink(qphot_output)

            # Filter qphot's stderr to convert missing EXPTIME keyword to a warning.
            # Note the two spaces before 'Keyword'
            regexp = (
                "Warning: Image (?P<msg>%s  Keyword: %s not found)"
                % (re.escape(self.path), re.escape(exptimek))
            )
            stderr = StreamToWarningFilter(sys.stderr, regexp, MissingFITSKeyword)

            # Run qphot on the image and save the output to our temporary file.
            kwargs = dict(
                cbox=cbox,
                annulus=annulus,
                dannulus=dannulus,
                aperture=aperture,
                coords=self.coords_path,
                output=qphot_output,
                exposure=exptimek,
                wcsin="world",
                interactive="no",
                Stderr=stderr,
            )
            apphot.qphot(self.path, **kwargs)
            assert Path(qphot_output).exists()

            # Extract selected fields with txdump to another temp file.
            txdump_fd, txdump_output = tempfile.mkstemp(
                prefix=Path(self.path).name, suffix=".qphot_txdump", text=True
            )
            os.close(txdump_fd)
            os.unlink(txdump_output)

            txdump_fields = ["xcenter", "ycenter", "mag", "sum", "flux", "stdev"]
            pyraf.iraf.txdump(
                qphot_output,
                fields=",".join(txdump_fields),
                Stdout=str(txdump_output),
                expr="yes",
            )

            # Parse txdump output: one line per object.
            with open(txdump_output, "rt") as txdump_fd:
                for line in txdump_fd:
                    fields = line.split()

                    # xcenter
                    try:
                        xcenter_str = fields[0]
                        xcenter = float(xcenter_str)
                        logging.debug("%s: xcenter = %.8f", self.path, xcenter)
                    except ValueError as e:
                        logging.debug("%s: can't convert xcenter '%s' (%s)", self.path, xcenter_str, e)
                        logging.debug("%s: xcenter set to -1 (fallback value)", self.path)
                        xcenter = -1.0

                    # ycenter
                    try:
                        ycenter_str = fields[1]
                        ycenter = float(ycenter_str)
                        logging.debug("%s: ycenter = %.8f", self.path, ycenter)
                    except ValueError as e:
                        logging.debug("%s: can't convert ycenter '%s' (%s)", self.path, ycenter_str, e)
                        logging.debug("%s: ycenter set to -1 (fallback value)", self.path)
                        ycenter = -1.0

                    # magnitude
                    try:
                        mag_str = fields[2]
                        mag = float(mag_str)
                        logging.debug("%s: mag = %.5f", self.path, mag)
                    except ValueError:
                        # float("INDEF") raises; treat as None
                        assert fields[2] == "INDEF"
                        logging.debug("%s: mag = None ('INDEF')", self.path)
                        mag = None

                    sum_ = float(fields[3])
                    logging.debug("%s: sum = %.5f", self.path, sum_)
                    flux = float(fields[4])
                    logging.debug("%s: flux = %.5f", self.path, flux)

                    try:
                        stdev_str = fields[5]
                        stdev = float(stdev_str)
                        logging.debug("%s: stdev = %.5f", self.path, stdev)
                    except ValueError:
                        assert fields[5] == "INDEF"
                        logging.debug("%s: stdev = None ('INDEF')", self.path)
                        stdev = None

                    self.append(QPhotResult(xcenter, ycenter, mag, sum_, flux, stdev))

        finally:
            # Remove temporary files if they were created.
            try:
                clean_tmp_files(qphot_output)
            except NameError:
                pass
            try:
                clean_tmp_files(txdump_output)
            except NameError:
                pass

        return len(self)


def get_coords_file(coordinates, year, epoch):
    """Return a temp file containing (proper-motion corrected) positions."""
    fd, path = tempfile.mkstemp(
        prefix=f"{year:.6f}_", suffix=f"_J{epoch}.coords", text=True
    )
    try:
        fmt = "%.10f\t%.10f\n"
        for coord in coordinates:
            # If both proper motions are provided and non-zero, correct the coords.
            if None in (coord.pm_ra, coord.pm_dec):
                assert coord.pm_ra is None
                assert coord.pm_dec is None

            if coord.pm_ra or coord.pm_dec:
                coord = coord.get_exact_coordinates(year, epoch=epoch)

            line = fmt % coord[:2]
            os.write(fd, line.encode("utf-8"))
    finally:
        os.close(fd)
    return path


def run(
    img,
    coordinates,
    epoch,
    aperture,
    annulus,
    dannulus,
    maximum,
    datek,
    timek,
    exptimek,
    uncimgk,
    cbox=0,
):
    """Do photometry on a FITS image."""
    kwargs = dict(date_keyword=datek, time_keyword=timek, exp_keyword=exptimek)

    # Determine observation year only if proper motions are present.
    for coord in coordinates:
        if coord.pm_ra or coord.pm_dec:
            try:
                year = img.year(**kwargs)
                break
            except KeyError as e:
                # Include the missing FITS keyword in the exception message
                match = re.search(r"keyword '(?P<keyword>.*?)' not found", str(e))
                assert match is not None
                msg = (
                    f"{img.path}: keyword '{match.group('keyword')}' not found. "
                    "It is needed in order to apply proper-motion correction, as one "
                    "or more astronomical objects have known proper motions"
                )
                raise KeyError(msg)
    else:
        # No object has a known proper motion; use epoch to keep coords unchanged.
        year = epoch

    # Proper-motion corrected coordinates file
    coords_path = get_coords_file(coordinates, year, epoch)

    img_qphot = QPhot(img.path, coords_path)
    img_qphot.run(annulus, dannulus, aperture, exptimek, cbox=cbox)

    # Build a saturation mask and check saturation via aperture photometry.
    if not uncimgk:
        orig_img_path = img.path
    else:
        orig_img_path = img.read_keyword(uncimgk)
        if not Path(orig_img_path).exists():
            msg = "image %s (keyword '%s' of image %s) does not exist"
            args = orig_img_path, uncimgk, img.path
            raise OSError(msg % args)

    try:
        # Temporary file to which the saturation mask is saved
        basename = Path(orig_img_path).name
        mkstemp_prefix = f"{basename}_satur_mask_{maximum}_ADUS_"
        mask_fd, satur_mask_path = tempfile.mkstemp(
            prefix=mkstemp_prefix, suffix=".fits", text=True
        )
        os.close(mask_fd)
        # IRAF won't overwrite; we want it to create the file.
        os.unlink(satur_mask_path)

        # Expression for imexpr. The space after ':' avoids sexagesimal parsing.
        expr = f"a>{maximum} ? 1 : 0"
        logging.debug("%s: imexpr = '%s'", img.path, expr)
        logging.debug("%s: a = %s", img.path, orig_img_path)
        logging.info("%s: Running IRAF's imexpr...", img.path)
        pyraf.iraf.images.imexpr(
            expr,
            a=orig_img_path,
            output=satur_mask_path,
            verbose="yes",
            Stdout=LoggerWriter("debug"),
        )
        assert Path(satur_mask_path).exists()
        logging.info("%s: IRAF's imexpr OK", img.path)
        logging.debug("%s: imexpr output = %s", img.path, satur_mask_path)

        # If cbox != 0, qphot re-centered objects; convert back to RA/Dec.
        if cbox:
            # Replace coords_path with re-centered world coordinates
            try:
                os.unlink(coords_path)
            except FileNotFoundError:
                pass
            fd, coords_path = tempfile.mkstemp(
                prefix=f"{Path(img.path).stem}_", suffix="_satur.coords", text=True
            )
            try:
                for object_phot in img_qphot:
                    centered_x, centered_y = object_phot.x, object_phot.y
                    ra, dec = img.pix2world(centered_x, centered_y)
                    os.write(fd, f"{ra} {dec}\n".encode("utf-8"))
            finally:
                os.close(fd)

        mask_qphot = QPhot(satur_mask_path, coords_path)
        # No centering this time; coordinates already re-centered if needed.
        mask_qphot.run(annulus, dannulus, aperture, exptimek, cbox=0)

        # We no longer need the coords file
        try:
            os.unlink(coords_path)
        except FileNotFoundError:
            pass

        assert len(img_qphot) == len(mask_qphot)
        for object_phot, object_mask in zip(img_qphot, mask_qphot):
            if __debug__ and not cbox:
                # When cbox == 0, coordinates should match exactly
                assert object_phot.x == object_mask.x
                assert object_phot.y == object_mask.y
            if object_mask.flux > 0:
                # Saturated -> magnitude set to +infinity
                idx = img_qphot.index(object_phot)
                img_qphot[idx] = object_phot._replace(mag=float("inf"))

    finally:
        # Remove saturation mask if it exists
        try:
            clean_tmp_files(satur_mask_path)
        except NameError:
            pass

    return img_qphot
